### ISSUE TITLE
Question: Restrict to full word matches

### ISSUE THREAD

**Issue by Dashue** [codyparker/react-transform-words#1]
Hey, this library is just what I'm looking for with the exception of the word matching.
I'm looking to match on full words only and not partial matching, is this something that's possible today or easy to add?

Thanks

**Comment by codyparker** [comment]
Hey - yeah, that's fairly easy to add. With regex it would be something like passing in: ```\bdog\b``` would match dog, but not hotdog. But right now it's escaping any regex characters (except pipe currently), so passing that in would create a search term wouldn't match anything.

I think I'll add in an option you could include with each word indicating if it's regex, to avoid escaping those characters. 

I'll try to get that added tonight, but it may be tomorrow before it's updated. I hope that helps.

**Comment by Dashue** [comment]
Hey Cody, thanks for your time. I actually can't use this as at the time I
didn't realize it didn't handle html very well.

Thanks

**Comment by codyparker** [comment]
No problem - I'll go ahead and push up the regex format change anyway.

When you say it doesn't handle HTML very well, are you trying to parse a string of HTML and highlight bits of it? Or do you mean it's not working as expected for you in some way?

**Comment by Dashue** [comment]
Yep exactly, it came out displaying the html tags as well <p>. So it seems to treat the html as text and render it back out as text. Maybe I'm doing it wrong?

**Comment by codyparker** [comment]
Yeah, it basically expects a string to parse, not full HTML. However, now that there is a regex format option, I'm sure it could be used to ignore HTML tags and just find the plain text.

I haven't really tested it much, but this seems to work and will ignore HTML tags and element attributes: 
```(?<!</?[^>]*|&[^;]*)matchthis```

So, you just need to replace matchthis with what you're searching for and it _should_ find only regular text from the part you passed in. And to make it work by finding only entire words, you could use [word boundaries](https://www.rexegg.com/regex-boundaries.html#wordboundary)

Hope that helps.
